import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Sidebar from '@/components/sidebar'
import Navbar from '@/components/navbar'
import { ClerkProvider, SignedIn, SignedOut, SignIn, UserButton } from '@clerk/nextjs'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Main layout container */}
          <div className='flex flex-col h-screen'>
            
            {/* Navbar at the top */}
            <div className='h-16 z-10 w-full mb-6'>
              <Navbar />
            </div>

            {/* Flex container for sidebar and main content */}
            <div className='flex flex-1 w-full'>
              
              {/* Sidebar taking full height */}
              <Sidebar />

              {/* Main content area */}
              <main className='flex-1 overflow-y-auto w-full px-4 md:px-8 lg:px-20 mt-8'>
                
                {/* Header inside main content */}
                <header className="flex justify-between items-center mb-6">
                  <h1>Clover Corp</h1>
                  <UserButton showName />
                </header>

                {/* Render the children here */}
                {children}
              </main>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
