import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from '@/components/sidebar'
import Navbar from '@/components/navbar'
import { MainNav } from '@/components/main-nav'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex flex-col h-screen'>
          <div className='h-16 z-10 w-full mb-6'>
            <Navbar />
          </div>
          <div className='flex flex-col md:flex-row flex-1 border-b border'>
            <Sidebar />
            <div className='md:w-3/4 p-4 overflow-y-auto'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
